### ISSUE TITLE
rename this repo to labdao.com for clarity

### ISSUE THREAD

**Issue by NiklasTR** [labdao/labdao.com#16]
With openlab.tools coming into focus, I would like us to rename this repo to avoid confusion. 
In the future there would be a link to openlab.tools with a button "open app" (the openlab.tools website would reference back to the labdao.com site as well)

**Comment by jlevers** [comment]
@blahah @janzheng i just renamed it -- you'll need to run `git remote set-url origin git@github.com:labdao/labdao.com.git`.
