### ISSUE TITLE
Adding an explicit newsletter link to our homepage

### ISSUE THREAD

**Issue by bjdyakov** [labdao/labdao.com#17]
Currently we only have a subscription box for our newsletter on our website. Could we add a button that links to here: https://newsletter.labdao.com/

I think people might want to take a look at our newsletter before subscribing. I just got this idea because I wanted to find newsletter issue #1, but googling "labdao newsletter" did not yield the above site in the first few links.

In the past I had to go to our twitter to get there. I did discover that clicking "subscribe" without an email entered can also bring us to the newsletter archive, but it's not very intuitive.

**Comment by NiklasTR** [comment]
Good point. 
<img width="847" alt="image" src="https://user-images.githubusercontent.com/18559148/158789054-47c0719a-c0ed-4768-94f6-22d92e07902e.png">

We could add two extra sentences:

Read the [Newsletter](https://newsletter.labdao.com/) first. Contribute to the Newsletter on [GitHub](https://github.com/labdao/newsletter). By subscribing, you agree with Revue’s [Terms of Service](https://www.getrevue.co/terms) and [Privacy Policy](https://www.getrevue.co/privacy).

**Comment by NiklasTR** [comment]
assigning @jlevers - can you take point here?

**Comment by jlevers** [comment]
yessir you got it

**Comment by jlevers** [comment]
Done in #18.
